name: Frontend CI

on:
  push:
    branches:
      - development
      - 'release/*'
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - development
      - 'release/*'
    paths:
      - 'frontend/**'

jobs:
  lint-and-build:
    name: Lint & Build (Node / Vite)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recomendado: LTS actual (ajusta si usas 22 a propósito)
          cache: 'npm'

      - name: Install dependencies
        working-directory: frontend/FinanceApp
        run: npm ci

      - name: Run linter
        working-directory: frontend/FinanceApp
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script defined, skipping..."
          fi

      - name: Build
        working-directory: frontend/FinanceApp
        run: npm run build

